tour.out: tour.c
	gcc tour.c -o tour.out && ./tour.out

play.out: play.c
	gcc play.c -o play.out && ./play.out

flight.out: flight_operators.c
	gcc flight_operators.c -o flight.out && ./flight.out < islands.txt

