find.out: find.c
	gcc find.c -o find.out && ./find.out;
	rm find.out

sort.out: sort.c
	gcc sort.c -o sort.out && ./sort.out
	rm sort.out

mysort.out: mysort.c
	gcc mysort.c -o mysort.out && ./mysort.out
	rm mysort.out

