fish.out: fish.c
	gcc fish.c -o fish.out && ./fish.out

chained.out: chained_structs.c
	gcc chained_structs.c -o chained.out && ./chained.out

acquarium.out: acquarium.c
	gcc acquarium.c -o acquarium.out && ./acquarium.out

scuba.out: scuba.c
	gcc scuba.c -o scuba.out && ./scuba.out

turtle.out: turtle.c
	gcc turtle.c -o turtle.out && ./turtle.out 